---
# tasks file for nexus_role
- name: Create Nexus user
  user:
    name: nexus
    system: yes
    shell: /bin/bash
    create_home: yes

- name: Download Nexus
  get_url:
    url: "https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
    dest: /tmp/nexus.tar.gz

- name: Extract Nexus
  unarchive:
    src: /tmp/nexus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Rename Nexus directory
  command: mv /opt/nexus-3.75.1-01 /opt/nexus

- name: Set permissions
  file:
    path: /opt/nexus
    owner: nexus
    group: nexus
    recurse: yes

- name: Configure Nexus service
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

- name: Reload systemd and enable Nexus service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: nexus
    state: started
